global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'eureka-services'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: 'http://host.docker.internal:8761/eureka'
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: job
      - source_labels: [__meta_eureka_instance_hostname]
        target_label: instance

rule_files:
  - "alert.rules.yml"
