services:
  inventory:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5431/ms_inventory
      SPRING_DATASOURCE_USERNAME: imagina
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db-inventory
    networks:
      - inventory
  db-inventory:
    container_name: db_inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: imagina
      POSTGRES_PASSWORD: 1234
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431
    volumes:
      - ./inventory_data:/var/lib/postgresql/data
    networks:
      - inventory
networks:
  inventory:
    name: inventory-network
