version: '3.7'
services:
  db-products:
    container_name: db_products
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: imagina
      POSTGRES_PASSWORD: 1234
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  db-inventory:
    container_name: db_inventory
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: imagina
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  db-orders:
    container_name: db_orders
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_orders
      POSTGRES_USER: imagina
      POSTGRES_PASSWORD: 1234
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

  db-payments:
    container_name: db_payments
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_payments
      POSTGRES_USER: imagina
      POSTGRES_PASSWORD: 1234
    ports:
      - 5434:5434
    expose:
      - 5434
    command: -p 5434